service: bref2-bench-function

provider:
    name: aws
    region: us-east-2
    versionFunctions: false
    tracing:
        lambda: true
    logs:
        httpApi:
            format: '{ "requestId": "$context.requestId", "routeKey": "$context.routeKey", "requestTime": "$context.requestTime", "integrationLatency": "$context.integrationLatency" }'

plugins:
    - ./vendor/bref/bref

functions:
    128:
        handler: index.php
        memorySize: 128
        runtime: php-83
    512:
        handler: index.php
        memorySize: 512
        runtime: php-83
    1024:
        handler: index.php
        memorySize: 1024
        runtime: php-83
    1769:
        handler: index.php
        memorySize: 1769
        runtime: php-83

    128-arm:
        handler: index.php
        memorySize: 128
        architecture: arm64
        runtime: php-83
    512-arm:
        handler: index.php
        memorySize: 512
        architecture: arm64
        runtime: php-83
    1024-arm:
        handler: index.php
        memorySize: 1024
        architecture: arm64
        runtime: php-83
    1769-arm:
        handler: index.php
        memorySize: 1769
        architecture: arm64
        runtime: php-83
