service: bref2-bench-laravel

provider:
    name: aws
    region: us-east-2
    versionFunctions: false
    environment:
        APP_ENV: production
        APP_KEY: 'base64:E+encJrg6dTOlxvvwmI081w7fiESSe8uljgzcOeU2HM='
        SESSION_DRIVER: cookie
    tracing:
        lambda: true
    logs:
        httpApi:
            format: '{ "requestId": "$context.requestId", "routeKey": "$context.routeKey", "requestTime": "$context.requestTime", "integrationLatency": "$context.integrationLatency" }'
    ecr:
        images:
            laravel:
                path: ./

plugins:
    - ./vendor/bref/bref

functions:
    1024:
        handler: public/index.php
        memorySize: 1024
        runtime: php-83-fpm
        events:
            -   httpApi: 'GET /1024'

    1024-arm:
        handler: public/index.php
        memorySize: 1024
        architecture: arm64
        runtime: php-83-fpm
        events:
            -   httpApi: 'GET /1024-arm'

    1024-container:
        image:
            name: laravel
        memorySize: 1024
        events:
            -   httpApi: 'GET /1024-container'

package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/css/**'
        - '!resources/js/**'
        - '!storage/**'
        - '!tests/**'
        - '!.env'
